# Generated by Django 3.0.5 on 2020-05-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_titles_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
    ]
